# Generated by Django 3.2.8 on 2021-12-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuestionario',
            name='version de cuestionario',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='finalizado', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='cuestionario',
            constraint=models.UniqueConstraint(fields=('organizacion', 'tipo_de_inspeccion', 'version'), name='version_de_cuestionario'),
        ),
    ]
