# Generated by Django 4.0.3 on 2022-03-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0002_auto_20211208_2047'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activo',
            name='inspecciones_activo_natural_key',
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(fields=('identificador', 'organizacion'), name='inspecciones_activo_natural_key'),
        ),
    ]
