# Generated by Django 4.0.3 on 2022-03-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0003_remove_activo_inspecciones_activo_natural_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
