# Generated by Django 4.0.3 on 2022-03-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0004_alter_activo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='avance',
            field=models.FloatField(default=0.0),
        ),
    ]
